baseURL = 'https://priyansh-jain06.github.io/'
languageCode = 'en-us'
title = 'Priyansh Jain'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "Priyansh Jain"
keywords = [ "Blog", "Portfolio" ]
author = "Me"
DateFormat = "March 17, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
enableLatex = true

[params.profileMode]
  enabled = true
  title = "Priyansh Jain"
  imageUrl = "/img/priyansh.jpg"
  imageWidth = 120
  imageHeight = 120
  subtitle = "First-Year Law Student [**RGNUL**](https://www.rgnul.ac.in/)."

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "achievements"
name = "achievements"
url = "/achiev/"
weight = 30

[[menu.main]]
identifier = "publications"
name = "publications"
url = "/publications/"
weight = 20

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts/"
weight = 35

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 40

pygmentsUseClasses = true

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true


