name = "Publish to GH Pages"

[on]
  [on.push]
  branches = [ "main" ]

[jobs.deploy]
runs-on = "ubuntu-latest"

  [[jobs.deploy.steps]]
  name = "Checkout source"
  uses = "actions/checkout@v3"

    [jobs.deploy.steps.with]
    submodules = true

  [[jobs.deploy.steps]]
  name = "Checkout destination"
  uses = "actions/checkout@v3"
  if = "github.ref == 'refs/heads/main'"

    [jobs.deploy.steps.with]
    ref = "gh-pages"
    path = "built-site"

  [[jobs.deploy.steps]]
  name = "Setup Hugo"
  run = """
curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.140.1/hugo_0.140.1_linux-amd64.tar.gz'
tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo          
"""

  [[jobs.deploy.steps]]
  name = "Build"
  run = "${RUNNER_TEMP}/hugo"

  [[jobs.deploy.steps]]
  name = "Deploy"
  if = "github.ref == 'refs/heads/main'"
  run = """
cp -R public/* ${GITHUB_WORKSPACE}/built-site/
cd ${GITHUB_WORKSPACE}/built-site
git add .
git config user.name 'jain-priyansh06'
git config user.email 'localrame@gmail.com'
git commit -m 'Updated site'
git push          
"""
